name: Pipeline Testes Automatizados Unitários Calculadora Ruby
# executa o workflow toda vez que for realizado um push ou pull-request no repositório
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # permite também executar esse workflow manualmente na aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  ruby-teste-unitario:
    # agente de execução/runner do tipo máquina virtual bem enxuta, sem interface gráfica
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1 - Obter cópia do código-fonte do repositório
        uses: actions/checkout@v3

      - name: Passo 2 - Instalar ruby e Instalar dependências 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          # executa o comando bundle install e armazena as gems instaladas automaticamente
          bundler-cache: true
          
      - name: Passo 3 - Executar testes automatizados unitários diretamente no código-fonte e Gerar relatório html 
        run: bundle exec rspec spec/tests/*
   
      - name: Passo 4 - Armazenar relatório html
        uses: actions/upload-artifact@v3
        # expressão condicional para que sempre seja executado independentemente dos resultados dos steps anteriores
        if: ${{ always() }}
        with: 
            name: relatorio-testes-unitarios-calculadora-ruby
            path: ./relatorios/relatorio-testes-unitarios-calculadora-ruby.html
            # armazena o relatório html por 30 dias
            retention-days: 30
